# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f3812945a8c63c95d606ed418a79514eeb593c760c82b6eff7c88a37caba0b1d4ea8b8efdb127e6a9f870eb880fb0a512d6019a115671b87dff68a0ca65e751

test:
  secret_key_base: 62c4ed6363dd9ccc91d4c170b24b84fd95f54142fda66ab482dddad44789d3e732d5e196bd672bcfd391b3c8bf5c6b03c4985dcb03acfd3e2a16ed38f4053c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
